<?php
    require "header.phtml";
?>
<main>
    <section class="about-page">
        <h2>À propos de La Joie Exotique</h2>
        <p>La Joie Exotique est une boutique exotique située au Mail à Rennes. Nous sommes fiers de servir notre communauté depuis plus de 10 ans, en offrant une large gamme de produits exotiques qui reflètent la diversité et la richesse des cultures du monde entier.</p>
        <p>Que vous cherchiez des épices rares, des produits alimentaires authentiques ou des cosmétiques naturels, vous trouverez tout ce dont vous avez besoin à La Joie Exotique. Notre mission est de fournir à nos clients des produits de haute qualité et un service exceptionnel.</p>
        <p>Nous sommes ravis de vous annoncer que vous pouvez désormais faire vos courses en ligne grâce à notre application. Profitez de la commodité de faire vos achats depuis chez vous et découvrez notre gamme complète de produits exotiques en quelques clics.</p>
    </section>
</main>