<?php
    require "adminHeader.phtml";
?>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-font-size">
        <li class="breadcrumb-item active" aria-current="page">Accueil</li>
        <li class="breadcrumb-item"><a href="index.php?route=show-orders">Commandes</a></li>
        <li class="breadcrumb-item"><a href="index.php?route=admin-inventory">Inventaire</a></li></li>
    </ol>
</nav>
<div class="admin-header">
    <section class="admin-content">
        <h2>Bienvenue sur la page d'administration</h2>
        <p>Veuillez sélectionner une option dans le menu pour commencer.</p>
    </section>
</div>

<div class="admin-main ">
    <nav class="admin-nav">
        <ul>
            <li><a href="index.php?route=show-orders">Commandes</a></li>
            <li><a href="index.php?route=add-product">Ajouter produit</a></li>
            <li><a href="index.php?route=admin-inventory">Inventaires</a></li>
        </ul>
    </nav>

</div>