<?php
    require "adminHeader.phtml";
?>
<div class="admin-header">
    <section class="admin-content">
        <h2>Bienvenue sur la page d'administration</h2>
        <p>Veuillez sélectionner une option dans le menu pour commencer.</p>
    </section>
</div>

<div class="admin-main ">
    <nav class="admin-nav">
        <ul>
            <li><a href="index.php?route=show-orders">Commandes</a></li>
            <li><a href="index.php?route=add-product">Ajouter produit</a></li>
            <li><a href="index.php?route=admin-inventory">Inventaires</a></li>
        </ul>
    </nav>

</div>