<?php
    require "adminHeader.phtml";
?>
<!-- templates/adminOrders.phtml -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-font-size">
        <li class="breadcrumb-item"><a href="index.php?route=admin">Accueil</a></li>
        <li class="breadcrumb-item active" aria-current="page">Commandes</li>
        <li class="breadcrumb-item"><a href="index.php?route=admin-inventory">Inventaire</a></li></li>
    </ol>
</nav>
<section class="admin-orders">
    <h2>Commandes</h2>
    <?php if (isset($data['orders']) && !empty($data['orders'])): ?>
        <table>
            <thead>
                <tr>
                    <th class="hidden-column">ID Commande</th>
                    <th>Nom du Client</th>
                    <th>Date</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data['orders'] as $order): ?>
                    <tr>
                        <td class="hidden-column"><?= $order->getId(); ?></td>
                        <td><?= $order->getUserId() ? $order->getUserName() : $order->getGuestName(); ?></td>
                        <td><?= $order->getCreatedAt()->format('Y-m-d H:i:s'); ?></td>
                        <td><?= $order->getTotalPrice(); ?> €</td>
                        <td><?= $order->getStatus(); ?></td>
                        <td>
                            <a href="index.php?route=order-details&order_id=<?= $order->getId(); ?>">Voir</a>
                            <a href="index.php?route=update-order-status&order_id=<?= $order->getId(); ?>"><i class="fa-solid fa-edit"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p>Aucune commande trouvée.</p>
    <?php endif; ?>
</section>