<footer>
<!-- Social media links -->
    <div>
        <a href="#" aria-label="Facebook"><i class="fa-brands fa-square-facebook"></i></a>
        <a href="#" aria-label="Instagram"><i class="fa-brands fa-square-instagram"></i></a>
    </div>
      
    <!-- Pages link -->
    <a href="index.php?route=legal-notice" aria-label="Mentions légales">Mentions légales</a>
    <a href="index.php?route=privacy-policy" aria-label="Politique de confidentialité">Politique de confidentialité</a>
      
    <!-- Copyright -->
    <p>Copyright &copy; <?= date('Y') ?> La Joie Exotique.</p>
</footer>