<?php
    require "header.phtml";
?>

<div class="home-page-div">
    <!-- Search bar -->
    <form class="search-bar" action="index.php?route=search-product" method="GET">
        <input type="hidden" name="route" value="search-product">
        <!-- Input field for entering the product name -->
        <input type="search" name="keyword" id="keyword" placeholder="Rechercher produit">
        <!-- Submit button for initiating the search -->
        <button class="search-button" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
    <div class="home-img-div">
        <img class="img-far-home" src="./images/homeImg.png" alt="Image de divers produits exotiques disponibles dans notre boutique en ligne">
    </div>
    <?php foreach ($data['productsCategoryArray'] as $categoryData): ?>
        <h2 class="category-name">
            <a href="index.php?route=category-products&category_id=<?= $categoryData['category']->getId(); ?>">
                <?= $categoryData['category']->getName(); ?>
            </a>
        </h2>
        <ul class="category-product-image">
            <?php foreach ($categoryData['products'] as $product): ?>
            <li>
                <a href="index.php?route=product&product_id=<?= $product->getId(); ?>">
                <?php foreach ($product->images as $image): ?>
                <div class="home-img-slide"><img src="<?= $image->getFileName(); ?>" alt="<?=$image->getAlt(); ?>"></div>
                <?php endforeach; ?>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php endforeach; ?>
</div>
<?php
    require "footer.phtml";
?>



