<?php
    require "adminHeader.phtml";
?>
<!-- templates/orderConfirmation.phtml -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-font-size">
        <li class="breadcrumb-item"><a href="index.php?route=admin">Accueil</a></li>
        <li class="breadcrumb-item"><a href="index.php?route=add-product">Ajouter produit</a></li>
        <li class="breadcrumb-item"><a href="index.php?route=show-orders">Commandes</a></li>
        <li class="breadcrumb-item"><a href="index.php?route=admin-inventory">Inventaire</a></li></li>
    </ol>
</nav>
<div class="admin-order-page">
    <section class="paiement-redirect admin-order-details"> 
        <h3>Details de la commande</h3>
        <table>
            <thead>
                <tr>
                    <th class="col-nom">Nom produit</th>
                    <th class="col-qty">Qté</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($orderProducts as $orderProduct): ?>
                    <tr>
                        <td class="col-nom"><?= htmlspecialchars($orderProduct['productName']) ?></td>
                        <td class="col-qty"><?= htmlspecialchars($orderProduct['quantity']) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <p class="order-total-amount"><strong>Total : <?= htmlspecialchars($order->getTotalPrice()) ?>€</strong></p>
    </section>
</div>