<!-- templates/paymentForm.phtml -->
<link rel="stylesheet" href="../assets/css/checkout.css">
<script src="assets/js/checkout.js" defer></script>
<section class="payment-style">
    <!-- Delivery options -->
    <div id="delivery-options" class="delivery-options">
        <h2>Options de Livraison</h2>
        <p>Veuillez choisir une option :</p>
        <button id="login-option" class="option-button">Se connecter avant de passer la commande</button>
        <button id="guest-option" class="option-button">Passer la commande sans se connecter</button>
    </div>

    <!-- payment form -->
    <form id="payment-form" class="hidden" action="index.php?route=payment-success" method="POST">
        <input type="hidden" name="route" value="payment-success">
        <input type="hidden" name="user-id" value="<?= isset($_SESSION["user"]) ? htmlspecialchars($_SESSION["user"]) : null; ?>">
        <h1>Paiement</h1>
        <fieldset class="fieldset-payment">
            <legend><label for="guest-name">Nom :</label></legend>
            <input type="text" id="guest-name" name="guest-name" placeholder="Votre nom" required>
            <legend><label for="city">City:</label></legend>
            <input type="text" id="city" name="city" placeholder="Ville" required>

            <legend><label for="postalCode">Postal Code:</label></legend>
            <input type="text" id="postalCode" name="postalCode" placeholder="Code postal" required>

            <legend><label for="street">Street:</label></legend>
            <input type="text" id="street" name="street" placeholder="Rue" required>

            <legend><label for="number">Number:</label></legend>
            <input type="text" id="number" name="number" placeholder="Numéro" required>

            <legend><label for="digicode-or-appt-name">Digicode or Apartment Name:</label></legend>
            <input type="text" id="digicode-or-appt-name" name="digicode-or-appt-name" placeholder="digicode ou nom figurant à la porte" required>
            
            <legend><label for="totalAmount">Prix total :</label></legend>
            <input type="text" id="total-amount" name="total-amount" value="<?= isset($_SESSION['totalAmount']) ? htmlspecialchars($_SESSION['totalAmount'])."€" : ''; ?>">
            
            <!-- Hidden fields for each product in the cart -->
            <?php 
            if (isset($_SESSION['product_details']) && is_array($_SESSION['product_details'])) {
                foreach ($_SESSION['product_details'] as $productId => $product) { ?>
                    <input type="hidden" name="products[<?= $productId ?>][product_id]" value="<?= htmlspecialchars($product['product_id']) ?>">
                    <input type="hidden" name="products[<?= $productId ?>][quantity]" value="<?= htmlspecialchars($product['quantity']) ?>">
                    <input type="hidden" name="products[<?= $productId ?>][subtotal]" value="<?= htmlspecialchars($product['subtotal']) ?>">
                <?php }
            }
            ?>
        </fieldset>
        <div id="payment-element">
            <!-- Stripe.js will inject the paiement element here -->
        </div>
        <button id="submit" disabled="disabled">
            <div class="spinner hidden" id="spinner"></div>
            <span id="button-text">Payer</span>
        </button>
        <div id="payment-message" class="hidden"></div>
    </form>
</section>